In [3]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [2]:
import psycopg as psql

ModuleNotFoundError: No module named 'psycopg'

In [13]:
conn = psql.connect(host = "localhost", dbname="geral",  user="manoel",  password="java2@mac")

In [14]:
cursor =  conn.execute

In [8]:
import pandas as pd


nome = "/home/manoelcarvalho/Me/Source/Edvaldo/AWS.xlsx"
planilha = 0
cab = 0

df = pd.read_excel(nome)

In [10]:
df

,Unnamed: 0,identity/LineItemId,identity/TimeInterval,bill/InvoiceId,bill/BillingEntity,bill/BillType,bill/PayerAccountId,bill/BillingPeriodStartDate,bill/BillingPeriodEndDate,lineItem/UsageAccountId,...,savingsPlan/SavingsPlanEffectiveCost,savingsPlan/AmortizedUpfrontCommitmentForBillingPeriod,savingsPlan/RecurringCommitmentForBillingPeriod,savingsPlan/StartTime,savingsPlan/EndTime,savingsPlan/OfferingType,savingsPlan/PaymentOption,savingsPlan/PurchaseTerm,savingsPlan/Region,resourceTags/aws:createdBy
0,0.0,as74seru3qmuxzfgxq6vtiiwmuahen3v6zwtf573qdp54g...,2021-06-21T18:00:00Z/2021-06-21T19:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,aj2kjueifsfg5oys4t3aqy3khizfsdoegaw5pawsmx73jw...,2021-06-06T17:00:00Z/2021-06-06T18:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AssumedRole:IHKQTZKDG4WTOXFURAORA:user.hackaton.5
2,2.0,aiyvgrr3cwd7bw6bowo2sby5rdrusyt6r2kn7t5sd32ukq...,2021-06-09T04:00:00Z/2021-06-09T05:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,qn3tu3yf6fs3ffucizrbovg5upkq7pqkkynfvbd2trggoi...,2021-06-19T10:00:00Z/2021-06-19T11:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,axbfzfgai37qg53exq7vskh6qc4zxpcmf5l4cm4udbkwuz...,2021-06-02T09:00:00Z/2021-06-02T10:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13528,13528.0,qup4fx33rkmzbgmnez2gnzzykax7fcnisjuuu45ux2qeng...,2021-06-23T11:00:00Z/2021-06-23T12:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13529,13529.0,aiyvgrr3cwd7bw6bowo2sby5rdrusyt6r2kn7t5sd32ukq...,2021-06-12T20:00:00Z/2021-06-12T21:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13530,13530.0,qoy2svrbb2qqxynic3ugpn3zybbxqhspruovjknvu2dvvo...,2021-06-03T19:00:00Z/2021-06-03T20:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AssumedRole:IHKQTZKDG4WTOXFURAORA:user.hackaton.6
13531,13531.0,aiyvgrr3cwd7bw6bowo2sby5rdrusyt6r2kn7t5sd32ukq...,2021-06-24T09:00:00Z/2021-06-24T10:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13532,13532.0,qhis3vunxumh5p5rbbj4vvk3etcfywedyf4mqxfjwzz6zk...,2021-06-28T08:00:00Z/2021-06-28T09:00:00Z,147634877.0,AWS,Anniversary,3.229633e+11,2021-06-01T00:00:00Z,2021-07-01T00:00:00Z,6.680334e+11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
produtos = df["product/ProductName"].unique()
print(produtos)
#for index, row in df.iterrows():
for row in produtos:
    print(row)

['AWS CloudTrail' 'Amazon Elastic Compute Cloud'
 'Amazon Virtual Private Cloud' 'Amazon DynamoDB'
 'Amazon Simple Storage Service' 'AmazonCloudWatch' 'AWS Systems Manager'
 'AWS Data Transfer']
AWS CloudTrail
Amazon Elastic Compute Cloud
Amazon Virtual Private Cloud
Amazon DynamoDB
Amazon Simple Storage Service
AmazonCloudWatch
AWS Systems Manager
AWS Data Transfer

In [22]:
import mysql.connector as mc

# Conexão com o banco 
cnx = mc.connect(user='escola', password='senha', host='127.0.0.1')

# Criação de cursos para execução de comandos SQL
cursor = cnx.cursor()

# Comandos para criação de tabelas 
criarTabelaProdutos = "CREATE TABLE IF NOT EXISTS unicap.tblProdutos(nome varchar(150), tipo varchar(50));"
criarTabelaInvoice = "CREATE TABLE IF NOT EXISTS unicap.tblInvoice(produto INT(10), DataInvoyce Date,  Valor DOUBLE);"
cursor.execute(criarTabelaProdutos)
cursor.execute(criarTabelaInvoice)

# Commit para confirmação dos comandos 
cnx.commit()
cursor.close()

True

In [45]:
#inserindo dados de produtos 
#dadosProdutos = "INSERT INTO unicap.tblProdutos(nome, tipo) VALUES (?,?); "
#for row in produtos:
#    cursor = cnx.cursor()
#    print(row)
#    cursor.execute(dadosProdutos, row, "AWS") 

cursor = cnx.cursor()
for row in produtos:
    dadosProdutos = "INSERT INTO unicap.tblProdutos(nome, tipo) VALUES ('" + str(row) + "', 'AWS'); "
    #print(dadosProdutos)
    cursor.execute(dadosProdutos) 
cnx.commit()
cursor.close()

True

In [59]:
 df.groupby('product/ProductName').aggregate({'lineItem/UnblendedCost':[sum]})

TypeError: can only concatenate str (not "float") to str

In [74]:

soma = 0
for index, row in df.iterrows():
    if not float(df['lineItem/UnblendedCost'].iloc[index]): 
        teste = df['lineItem/UnblendedCost'].iloc[index]
    else:    
        valor = float(df['lineItem/UnblendedCost'].iloc[index])
        soma = soma + valor

print(soma)

TypeError: float() argument must be a string or a number, not 'datetime.datetime'